### ISSUE TITLE
Pay fee without p2a and extra inputs

### ISSUE THREAD

**Issue by 1440000bytes** [stutxo/simple_ctv#1]
> Transaction Examples:
example of minimum possible fees with no extra input
[orignal fee spend: Parent Transaction on Mempool Space](https://mempool.space/signet/tx/8b0c09b92387ddbbea7ae2a8bca24e48a28551be4025c50ab74844ac8001077c)
[orignal fee spend: Child Transaction on Mempool Space](https://mempool.space/signet/tx/bf1e5af2e886a8f2072dcecad6cff1f736084983713bd32df606259e15bab67f)
example of adding extra input to cover the fees
[bump fee with extra input: Parent Transaction on Mempool Space](https://mempool.space/signet/tx/32f4f4e6165e7f8df9b9a762e11a6ca7f16087713e0e3e42352021e6bf3800e3)
[bump fee with extra input: Child Transaction on Mempool Space](https://mempool.space/signet/tx/9a3582f03b0ac39cff8ed024cf8f38e4fc4a1ee2ff216badf041bf4572c0d03b)

There is one more way to pay fees using 1p1c package and no p2a. Use the output from ctv spend (1337 sats) to pay its fees when spending.

**Comment by stutxo** [comment]
> > Transaction Examples:
> > example of minimum possible fees with no extra input
> > [orignal fee spend: Parent Transaction on Mempool Space](https://mempool.space/signet/tx/8b0c09b92387ddbbea7ae2a8bca24e48a28551be4025c50ab74844ac8001077c)
> > [orignal fee spend: Child Transaction on Mempool Space](https://mempool.space/signet/tx/bf1e5af2e886a8f2072dcecad6cff1f736084983713bd32df606259e15bab67f)
> > example of adding extra input to cover the fees
> > [bump fee with extra input: Parent Transaction on Mempool Space](https://mempool.space/signet/tx/32f4f4e6165e7f8df9b9a762e11a6ca7f16087713e0e3e42352021e6bf3800e3)
> > [bump fee with extra input: Child Transaction on Mempool Space](https://mempool.space/signet/tx/9a3582f03b0ac39cff8ed024cf8f38e4fc4a1ee2ff216badf041bf4572c0d03b)
> 
> There is one more way to pay fees using 1p1c package and no p2a. Use the output from ctv spend (1337 sats) to pay its fees when spending.



> Another way to pay the fees using 1p1c package: https://xcancel.com/1440000bytes/status/1868375944832156108

thanks, i added this as an example. Im trying to think of why i wouldn't just do this every time if i was the one spending. What are the privacy concerns? Also this means you have to add a higher minimum fee than 240 on the second output for it to propagate around the network as its not p2a? 

> There is one more way to pay fees using 1p1c package and no p2a. Use the output from ctv spend (1337 sats) to pay its fees when spending.

I added an example for this kind of spend but it hasnt found its way around the mempool yet. 

86896275fb71d4e3b84d1edeeacb90f7c4ccf77ee3a29e66d7effff4bb0682fb

this is the raw transaction if you can somehow help it along. Sometimes this takes forever to propagate

030000000001010c73835448c604c41820f12ef5702cfd1b5a9852bed01d60eeb3a41678e70abd0100000000fdffffff03a4010000000000001600142b27da1b51f845bf8994c0e05a312360416f8fe0f0000000000000000451024e730000000000000000296a27f09fa5aa206e6f20e29a93207472616e73616374696f6e206e6f2070726f626c656d20f09fa5aa0320f79d89eff665beb26c52d862f02aba2afda28607781a42e15023fd49be2cd45e2320f79d89eff665beb26c52d862f02aba2afda28607781a42e15023fd49be2cd45eb37521c1e60fe1ef82bcb2ca506a8cb7fe18cbe1b70048d1cfbb4075969269dbf2e38eea00000000

thanks!

**Comment by stutxo** [comment]
i guess this example is just to show if you really wanted to not create a second child transaction, you could still just deduct the fee from the other output, but i'm not sure what the use case of that would be. 

The anchor output has to stay or it wont satisfy the ctv hash 

was the other example you had in mind just removing the anchor output entirely from the ctv template? That would just be a normal fee paying transaction at that point? 

thanks!

**Comment by stutxo** [comment]
ah i see, il add an example for that. thanks 

i should probably add some cli commands where its easier to test all these different ways of spending
